blog/urls.py
from django.urls import path
from django.views.decorators.cache import never_cache

from blog.apps import BlogConfig
from blog.views import BlogCreateView, BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('create/', never_cache(BlogCreateView.as_view()), name='create'),
    path('', BlogListView.as_view(), name='list'),
    path('view/<int:pk>/', BlogDetailView.as_view(), name='view'),
    path('edit/<int:pk>/', never_cache(BlogUpdateView.as_view()), name='edit'),
    path('delete/<int:pk>/', BlogDeleteView.as_view(), name='delete')
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models


class Blog(models.Model):
    """Модель блога"""
    title = models.CharField(max_length=100, verbose_name='Заголовок')
    slug = models.CharField(max_length=100, verbose_name='slug', null=True, blank=True)
    content = models.TextField(verbose_name='Содержание')
    image = models.ImageField(upload_to='blog', verbose_name='Изображение', null=True, blank=True)
    date = models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')
    is_published = models.BooleanField(default=True, verbose_name='Опубликовано')
    views_count = models.IntegerField(default=0, verbose_name='Количество просмотров')
    email = models.EmailField(verbose_name='Почта', null=True, blank=True, unique=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Блог'
        verbose_name_plural = 'Блоги'
        permissions = [
            ('can_deactivate', 'can deactivate post'),
        ]

blog/forms.py
from django import forms
from django.forms import BooleanField

from blog.models import Blog


class StyleFormMixin:
    """Стилизация формы"""
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if isinstance(field, BooleanField):
                field.widget.attrs['class'] = 'form-check-input'
            else:
                field.widget.attrs['class'] = 'form-control'


class BlogForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Blog
        fields = ('title', 'content', 'image', 'email')


class BlogModeratorForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Blog
        fields = ('is_published',)

blog/views.py
from django.conf import settings
from django.core.exceptions import PermissionDenied
from django.core.mail import send_mail
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView
from pytils.translit import slugify

from blog.forms import BlogForm, BlogModeratorForm
from blog.models import Blog


class BlogCreateView(CreateView):
    model = Blog
    form_class = BlogForm
    success_url = reverse_lazy('blog:list')

    def form_valid(self, form):
        """Создание слага"""
        if form.is_valid():
            new_blog = form.save()
            new_blog.slug = slugify(new_blog.title)
            new_blog.save()
        return super().form_valid(form)


class BlogListView(ListView):
    model = Blog

    def get_queryset(self):
        """Вывод только опубликованных записей"""
        return super().get_queryset().filter(is_published=True)


class BlogDetailView(DetailView):
    model = Blog

    def get_object(self, queryset=None):
        """Увеличение количества просмотров записи"""
        """Отправка письма при просмотре записи 100 раз"""
        self.object = super().get_object(queryset)
        self.object.views_count += 1
        self.object.save()
        if self.object.views_count == 100:
            send_mail('Поздравляем, ваша запись просмотрена 100 раз!',
                      f'Запись {self.object.title} просмотрена 100 раз!',
                      settings.EMAIL_HOST_USER, [self.object.email])
        return self.object


class BlogUpdateView(UpdateView):
    model = Blog
    fields = ['title', 'content', 'image', 'is_published', 'email']
    success_url = reverse_lazy('blog:list')

    def form_valid(self, form):
        """Создание слага"""
        if form.is_valid():
            new_blog = form.save()
            new_blog.slug = slugify(new_blog.title)
            new_blog.save()
        return super().form_valid(form)

    def get_success_url(self):
        """Перенаправление на просмотр записи"""
        return reverse('blog:view', args=[self.kwargs.get('pk')])

    def get_form_class(self):
        """Выбор формы для редактирования блога"""
        user = self.request.user
        if user.has_perm('blog.can_deactivate'):
            return BlogModeratorForm
        raise PermissionDenied


class BlogDeleteView(DeleteView):
    model = Blog
    success_url = reverse_lazy('blog:list')

blog/templates/blog/blog_confirm_delete.html
{% extends 'catalog/base.html' %}

{% block content %}
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <p>Хотите удалить запись {{ object.title }}?</p>
                        <button type="submit" class="btn btn-success">Удалить</button>
                        <a class="btn btn-primary" href="{% url 'blog:list' %}" role="button">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

blog/templates/blog/blog_detail.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}
<div class="container">
  <div class="row text-center">
    <div class="col-9">
      <div class="card mb-4 box-shadow">
        <div class="card-header">
          <h4 class="my-0 font-weight-normal">{{ object.title }}</h4>
        </div>
        <div class="card-body">
          {% if object.image %}
          <img src="{{ object.image | media_filter }}">
          {% endif %}
          <h5 class="card-title pricing-card-title">{{ object.date }}</h5>
          <ul class="list-unstyled mt-3 mb-4 text-start m-3">
            <li>{{ object.content }}</li>
          </ul>
          <p>Количество просмотров: {{ object.views_count }}</p>
          <p>{{ object.slug }}</p>
          {% if perms.blog.can_deactivate %}
          <a class="btn btn-primary" href="{% url 'blog:edit' object.pk %}" role="button">Изменить</a>
          <a class="btn btn-primary" href="{% url 'blog:delete' object.pk %}" role="button">Удалить</a>
          {% endif %}
          <a class="btn btn-primary" href="{% url 'blog:list' %}" role="button">Назад</a>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

blog/templates/blog/blog_form.html
{% extends 'catalog/base.html' %}

{% block content %}
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">
                            {% if object %}
                                Изменить запись
                            {% else %}
                                Создать запись
                            {% endif %}
                        </button>
                        <a class="btn btn-primary" href="{% url 'blog:list' %}" role="button">Назад</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

blog/templates/blog/blog_list.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}

<div class="text-center mt-3">
  <h1>Off-Road Market</h1>
  <p>Все записи из блога:</p>
</div>
<div class="container">
  <div class="row text-center">
    {% for object in object_list %}
    {% if object.is_published %}
    <div class="col-6">
      <div class="card mb-4 box-shadow">
        <div class="card-header">
          <h4 class="my-0 font-weight-normal">{{ object.title }}</h4>
        </div>
        <div class="card-body">
          {% if object.image %}
          <img src="{{ object.image | media_filter }}" class="rounded mx-auto d-block w-100">
          {% endif %}
          <h5 class="card-title pricing-card-title">{{ object.date }}</h5>
          <ul class="list-unstyled mt-3 mb-4 text-start m-3">
            <li>{{ object.content | slice:":100" }}</li>
          </ul>
          <p>Количество просмотров: {{ object.views_count }}</p>
          <a class="btn btn-primary" href="{% url 'blog:view' object.pk %}" role="button">Просмотреть</a>
          <a class="btn btn-primary" href="{% url 'blog:delete' object.pk %}" role="button">Удалить</a>
        </div>
      </div>
    </div>
    {% endif %}
    {% endfor %}
  </div>
</div>
{% endblock %}