blog/urls.py
from django.urls import path
from django.views.decorators.cache import never_cache

from blog.apps import BlogConfig
from blog.views import BlogCreateView, BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('create/', never_cache(BlogCreateView.as_view()), name='create'),
    path('', BlogListView.as_view(), name='list'),
    path('view/<int:pk>/', BlogDetailView.as_view(), name='view'),
    path('edit/<int:pk>/', never_cache(BlogUpdateView.as_view()), name='edit'),
    path('delete/<int:pk>/', BlogDeleteView.as_view(), name='delete')
]

catalog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page, never_cache

from catalog.apps import CatalogConfig
from catalog.views import ProductListView, ProductDetailView, ProductCreateView, ContactsListView, ProductUpdateView, \
    ProductDeleteView, CategoryListView

app_name = CatalogConfig.name

urlpatterns = [
    path('', ProductListView.as_view(), name='home_page'),
    path('contacts/', ContactsListView.as_view(), name='contacts'),
    path('product/<int:pk>', cache_page(60)(ProductDetailView.as_view()), name='product_detail'),
    path('add_product', never_cache(ProductCreateView.as_view()), name='add_product'),
    path('product/update/<int:pk>', never_cache(ProductUpdateView.as_view()), name='update_product'),
    path('product/delete/<int:pk>', ProductDeleteView.as_view(), name='delete_product'),
    path('categories_list', CategoryListView.as_view(), name='categories_list'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/models.py
from django.db import models

from users.models import User

NULLABLE = {'blank': True, 'null': True}


class Category(models.Model):
    """Категория товара"""
    name = models.CharField(max_length=100, verbose_name='Название')
    description = models.TextField(verbose_name='Описание')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'


class Product(models.Model):
    """Товар"""
    name = models.CharField(max_length=100, verbose_name='Название')
    description = models.TextField(verbose_name='Описание')
    price = models.IntegerField(verbose_name='Цена')
    photo = models.ImageField(upload_to='catalog', **NULLABLE)
    created_at = models.DateField(verbose_name='Дата создания', auto_now_add=True, **NULLABLE)
    updated_at = models.DateField(verbose_name='Дата последнего изменения', auto_now=True, **NULLABLE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='Категория', **NULLABLE)
    seller = models.ForeignKey(User, on_delete=models.SET_NULL, verbose_name='seller', **NULLABLE)
    is_active = models.BooleanField(verbose_name='Прошел ли проверку', default=False)

    def __str__(self):
        return f'{self.name} - {self.price} руб'

    class Meta:
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'
        permissions = [
            ('can_deactivate', 'deactivate product'),
            ('can_edit_description', 'edit description product'),
            ('can_edit_category', 'edit category product'),
        ]


class Version(models.Model):
    """Версия товара"""
    product = models.ForeignKey(Product, verbose_name='Товар', on_delete=models.CASCADE)
    version = models.IntegerField(verbose_name='Версия')
    name = models.CharField(max_length=100, verbose_name='Название версии')
    activity = models.BooleanField(verbose_name='Активность версии', default=True)

    def __str__(self):
        return f'{self.product} - {self.version}'

    class Meta:
        verbose_name = 'Версия'
        verbose_name_plural = 'Версии'


class Contact(models.Model):
    """Контакты"""
    country = models.CharField(max_length=50, verbose_name='Страна')
    inn = models.IntegerField(verbose_name='ИНН')
    address = models.CharField(max_length=100, verbose_name='Адрес')

    def __str__(self):
        return f'{self.country}, {self.inn}, {self.address}'

    class Meta:
        verbose_name = 'Контакт'
        verbose_name_plural = 'Контакты'

catalog/forms.py
from django import forms
from django.forms import BooleanField

from catalog.models import Product, Version

FORBIDDEN_WORDS = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция', 'радар']


class StyleFormMixin:
    """Стилизация формы"""
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if isinstance(field, BooleanField):
                field.widget.attrs['class'] = 'form-check-input'
            else:
                field.widget.attrs['class'] = 'form-control'


class ProductForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Product
        exclude = ('created_at', 'updated_at', 'seller', 'is_active')

    def clean_name(self):
        """Валидация названия продукта"""
        cleaned_name = self.cleaned_data['name']
        if cleaned_name.lower() in FORBIDDEN_WORDS:
            raise forms.ValidationError('Нельзя использовать запрещенные слова')
        return cleaned_name

    def clean_description(self):
        """Валидация описания продукта"""
        cleaned_description = self.cleaned_data['description']
        if cleaned_description.lower() in FORBIDDEN_WORDS:
            raise forms.ValidationError('Нельзя использовать запрещенные слова')
        return cleaned_description


class ProductModeratorForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Product
        fields = ('description', 'category', 'is_active')


class VersionForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Version
        fields = '__all__'

catalog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.forms import inlineformset_factory
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from catalog.forms import ProductForm, VersionForm, ProductModeratorForm
from catalog.models import Product, Contact, Version, Category
from catalog.services import get_category_from_cache, get_products_from_cache
from configurations import APPEALS
import csv


class ProductListView(ListView):
    model = Product

    def get_context_data(self, **kwargs):
        """Возвращение последней активной версии товара в списке товаров"""
        context = super().get_context_data(**kwargs)
        products = Product.objects.all()
        for product in products:
            versions = Version.objects.filter(product=product)
            active_version = versions.filter(activity=True)
            if active_version:
                product.name_version = active_version.last().name
                product.number_version = active_version.last().version
        context['object_list'] = products
        return context

    def get_queryset(self):
        """Возвращение товаров из кэша"""
        return get_products_from_cache()


class ProductDetailView(DetailView):
    model = Product


class ProductDeleteView(DeleteView, LoginRequiredMixin):
    model = Product
    success_url = reverse_lazy('catalog:home_page')


class ProductCreateView(CreateView, LoginRequiredMixin):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('catalog:home_page')

    def form_valid(self, form):
        """Указываем почту продавца"""
        product = form.save()
        user = self.request.user
        product.seller = user
        product.save()
        return super().form_valid(form)


class ProductUpdateView(LoginRequiredMixin, UpdateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('catalog:home_page')

    def get_context_data(self, **kwargs):
        """Добавление версий товара при редактировании товара"""
        context_data = super().get_context_data(**kwargs)
        ProductFormset = inlineformset_factory(Product, Version, form=VersionForm, extra=1)
        if self.request.method == 'POST':
            context_data['formset'] = ProductFormset(self.request.POST, instance=self.object)
        else:
            context_data['formset'] = ProductFormset(instance=self.object)
        return context_data

    def form_valid(self, form):
        """Добавление версий товара при редактировании товара"""
        context_data = self.get_context_data()
        formset = context_data['formset']
        if form.is_valid() and formset.is_valid():
            self.object = form.save()
            formset.instance = self.object
            formset.save()
            return super().form_valid(form)
        else:
            return self.render_to_response(self.get_context_data(form=form, formset=formset))

    def get_form_class(self):
        """Выбор формы для редактирования товара"""
        user = self.request.user
        if user == self.object.seller:
            return ProductForm
        if user.has_perm('catalog.can_deactivate') and user.has_perm('catalog.can_edit_description') and user.has_perm('catalog.can_edit_category'):
            return ProductModeratorForm
        raise PermissionDenied


class ContactsListView(ListView):
    model = Contact

    def get_queryset(self):
        """Выбор последней записи из таблицы контактов"""
        qs = super().get_queryset()
        max_pk = 0
        for item in qs:
            if item.pk > max_pk:
                max_pk = item.pk
        qs = qs.filter(pk=max_pk)
        return qs

    def post(self, request, *args, **kwargs):
        """Запись заявки в csv файл и перенаправление на главную страницу"""
        name = request.POST.get('name')
        phone = request.POST.get('phone')
        message = request.POST.get('message')
        data_to_write = {"name": name, "phone": phone, "message": message}
        print(f'{name} просит связаться по номеру {phone}. Его вопрос: {message}')
        with open(APPEALS, "a") as file:
            fc = csv.DictWriter(file, fieldnames=data_to_write.keys())
            fc.writerow(data_to_write)
        return redirect(reverse_lazy('catalog:home_page'))


class CategoryListView(ListView):
    model = Category

    def get_queryset(self):
        """Возвращение категорий из кэша"""
        return get_category_from_cache()

catalog/templates/catalog/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ title }}</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
  </head>
  <body>
  {% include 'catalog/includes/inc_menu.html' %}
  {% block content %}
  {% endblock %}

  <div class="row mt-5 border-top">
    <div class="col-3">
      <p>Off-Road Market</p>
      <p class="text-muted">&copy; 2024</p>
    </div>
    <div class="col-3">
      <h5>Наши Услуги:</h5>
      <ul class="list-unstyled">
        <li class="list-group-item"><a href="#">Подбор оборудования</a></li>
        <li class="list-group-item"><a href="#">Установка оборудования</a></li>
        <li class="list-group-item"><a href="#">Отправка в регионы</a></li>
      </ul>
    </div>
    <div class="col-3">
      <h5>Мы в соц. сетях:</h5>
      <ul class="list-unstyled">
          <li class="list-group-item"><a href="#">ВКонтакте</a></li>
          <li class="list-group-item"><a href="#">Telegram</a></li>
          <li class="list-group-item"><a href="#">Instagram</a></li>
      </ul>
    </div>
    <div class="col-3">
      <h5>О нас:</h5>
      <ul class="list-unstyled">
          <li class="list-group-item"><a href="/contacts/">Контакты</a></li>
      </ul>
    </div>
  </div>
  <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
  </body>
</html>

catalog/templates/catalog/category_list.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}

<div class="text-center mt-3">
  <h1>Off-Road Market</h1>
  <p>Лидирующий магазин по продаже внедорожного тюнинга</p>
</div>
<div class="container">
  <div class="row text-center">
    {% for category in object_list %}
      <div class="col-6">
        <div class="card mb-4 box-shadow">
          <div class="card-header">
            <h4 class="my-0 font-weight-normal">{{ category.name }}</h4>
          </div>
          <div class="card-body">
            <h3 class="card-title pricing-card-title">{{ category.description }}</h3>
          </div>
        </div>
      </div>
    {% endfor %}
  </div>
</div>
{% endblock %}

catalog/templates/catalog/contact_list.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="text-center mt-3">
    <h1>Контакты</h1>
</div>
{% for contact in object_list %}
<div class="container">
    <div class="row">
        <div class="col-9 col-sm-offset-3">
            <div class="card">
                <div class="card-body">
                    <table class="table table-striped">
                        <tr>
                            <td>Страна</td>
                            <td>{{ contact.country }}</td>
                        </tr>
                        <tr>
                            <td>ИНН</td>
                            <td>{{ contact.inn }}</td>
                        </tr>
                        <tr>
                            <td>Адрес</td>
                            <td>{{ contact.address }}</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        {% include 'catalog/includes/inc_feedback.html' %}
    </div>
</div>
{% endfor %}
{% endblock %}

catalog/templates/catalog/home_page.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}

<div class="text-center mt-3">
  <h1>Off-Road Market</h1>
  <p>Лидирующий магазин по продаже внедорожного тюнинга</p>
</div>
<div class="container">
  <div class="row text-center">
    {% for product in products %}
    <div class="col-6">
      <div class="card mb-4 box-shadow">
        <div class="card-header">
          <h4 class="my-0 font-weight-normal">{{ product.name }}</h4>
        </div>
        <div class="card-body">
          <img src="{{ product.photo | media_filter }}" class="rounded mx-auto d-block">
          <h1 class="card-title pricing-card-title">{{ product.price }}</h1>
          <ul class="list-unstyled mt-3 mb-4 text-start m-3">
            <li>{{ product.description | slice:":100" }}</li>
          </ul>
          <a class="btn btn-primary" href="{% url 'catalog:product_detail' product.pk %}" role="button">Просмотреть</a>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</div>
{% endblock %}

catalog/templates/catalog/product_confirm_delete.html
{% extends 'catalog/base.html' %}

{% block content %}
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <p>Хотите удалить товар {{ object.name }}?</p>
                        <button type="submit" class="btn btn-success">Удалить</button>
                        <a class="btn btn-primary" href="{% url 'catalog:home_page' %}" role="button">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

catalog/templates/catalog/product_detail.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}
<div class="container">
  <div class="row text-center">
    <div class="col-9">
      <div class="card mb-4 box-shadow">
        <div class="card-header">
          <h4 class="my-0 font-weight-normal">{{ object.name }}</h4>
        </div>
        <div class="card-body">
          <img src="{{ object.photo | media_filter }}">
          <h1 class="card-title pricing-card-title">{{ object.price }}</h1>
          <ul class="list-unstyled mt-3 mb-4 text-start m-3">
            <li>{{ object.description }}</li>
          </ul>
          <a class="btn btn-primary" href="#" role="button">Купить</a>
          {% if perms.catalog.can_deactivate and perms.catalog.can_edit_description and perms.catalog.can_edit_category or user == object.seller %}
          <a class="btn btn-primary" href="{% url 'catalog:update_product' object.pk %}" role="button">Изменить</a>
          <a class="btn btn-primary" href="{% url 'catalog:delete_product' object.pk %}" role="button">Удалить</a>
          {% endif %}
          <a class="btn btn-primary" href="{% url 'catalog:home_page' %}" role="button">Назад</a>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

catalog/templates/catalog/product_form.html
{% extends 'catalog/base.html' %}
{% block content %}
<div class="container">
    <form class="row" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    {{ form.as_p }}
                </div>
                {% if object %}
                    <button type="submit" class="btn btn-primary mt-3">Изменить товар</button>
                {% else %}
                    <button type="submit" class="btn btn-primary mt-3">Добавить товар</button>
                {% endif %}
            </div>
        </div>
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    {{ formset.management_form }}
                    {% for form in formset.forms %}
                        {{ form.as_p }}
                    {% endfor %}
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock %}

catalog/templates/catalog/product_list.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}

<div class="text-center mt-3">
  <h1>Off-Road Market</h1>
  <p>Лидирующий магазин по продаже внедорожного тюнинга</p>
</div>
<div class="container">
  <div class="row text-center">
    {% for product in object_list %}
      <div class="col-6">
        <div class="card mb-4 box-shadow">
          <div class="card-header">
            <h4 class="my-0 font-weight-normal">{{ product.name }}</h4>
          </div>
          <div class="card-body">
            <img src="{{ product.photo | media_filter }}" class="rounded mx-auto d-block w-100">
            <h1 class="card-title pricing-card-title">{{ product.price }} руб</h1>
            <h3>{{ product.description | slice:":100" }}</h3>
            <ul class="list-unstyled mt-3 mb-4">
              <li>Версия номер {{ product.number_version }} - {{ product.name_version }}</li>
              <li>Продавец: {{ product.seller }}</li>
            </ul>
            <a class="btn btn-primary" href="{% url 'catalog:product_detail' product.pk %}" role="button">Просмотреть</a>
          </div>
        </div>
      </div>
    {% endfor %}
  </div>
</div>
{% endblock %}